import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { auth } from "@/auth";
import { CounterStoreProvider } from "@/providers/counter-store-provider";
import { redirect } from "next/navigation";
import Scroll from "@/components/ScrollToTop";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tuon's Next app boilerplate",
  description: "Generated by Tuon",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <Scroll />
        <CounterStoreProvider>
          <ReactQueryProvider>
            <ThemeProvider
              enableSystem
              defaultTheme="system"
              attribute="class"
            >
              <main>
                <Navbar />
                {children}
              </main>
            </ThemeProvider>
          </ReactQueryProvider>
        </CounterStoreProvider>
      </body>
    </html>
  );
}
